package com.hu.parser.ledparser.dao;

import com.hu.parser.ledparser.vo.LedPanel;
import com.hu.parser.ledparser.vo.LedPanelExample;
import com.hu.parser.ledparser.vo.LedPanelKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LedPanelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    long countByExample(LedPanelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    int deleteByExample(LedPanelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    int deleteByPrimaryKey(LedPanelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    int insert(LedPanel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    int insertSelective(LedPanel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    List<LedPanel> selectByExample(LedPanelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    LedPanel selectByPrimaryKey(LedPanelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") LedPanel record, @Param("example") LedPanelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    int updateByExample(@Param("record") LedPanel record, @Param("example") LedPanelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    int updateByPrimaryKeySelective(LedPanel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    int updateByPrimaryKey(LedPanel record);
}