package com.hu.parser.ledparser.vo;

public class LedPanelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.id
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.company
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.model
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.pitch
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private Float pitch;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.id
     *
     * @return the value of ledpanel.id
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.id
     *
     * @param id the value for ledpanel.id
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.company
     *
     * @return the value of ledpanel.company
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.company
     *
     * @param company the value for ledpanel.company
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.model
     *
     * @return the value of ledpanel.model
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.model
     *
     * @param model the value for ledpanel.model
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.pitch
     *
     * @return the value of ledpanel.pitch
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public Float getPitch() {
        return pitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.pitch
     *
     * @param pitch the value for ledpanel.pitch
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setPitch(Float pitch) {
        this.pitch = pitch;
    }
}