package com.hu.parser.ledparser.vo;

import java.util.Date;

public class LedPanel extends LedPanelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.brightness
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private Float brightness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.refresh_rate
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private Integer refreshRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.pixel_composition
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String pixelComposition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.Panel_dimension
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String panelDimension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.vertical_viewing_angle
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private Float verticalViewingAngle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.horizontal_viewing_angle
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private Float horizontalViewingAngle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.panel_weight
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private Float panelWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.application
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String application;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.ip_rating
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String ipRating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.Gray_scale
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private Integer grayScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.Panel_w_resolution
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String panelWResolution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.Panel_h_resolution
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String panelHResolution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.panel_resolution
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String panelResolution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.Tile_dimension
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String tileDimension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.tile_weight
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private Float tileWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.tile_w_resolution
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private Integer tileWResolution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.tile_h_resolution
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private Integer tileHResolution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.Panel_material
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String panelMaterial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.panel_flatness
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String panelFlatness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.calibration
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private Boolean calibration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.color_temperature
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String colorTemperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.contrast
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String contrast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.Power_consumption
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private Float powerConsumption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.maintenance
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String maintenance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.certification
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String certification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.created_date
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.last_updated
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private Date lastUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.product_link
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String productLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.Operating_temperature
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String operatingTemperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.operating_RH
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String operatingRh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.others
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String others;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledpanel.picture
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    private String picture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.brightness
     *
     * @return the value of ledpanel.brightness
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public Float getBrightness() {
        return brightness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.brightness
     *
     * @param brightness the value for ledpanel.brightness
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setBrightness(Float brightness) {
        this.brightness = brightness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.refresh_rate
     *
     * @return the value of ledpanel.refresh_rate
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public Integer getRefreshRate() {
        return refreshRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.refresh_rate
     *
     * @param refreshRate the value for ledpanel.refresh_rate
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setRefreshRate(Integer refreshRate) {
        this.refreshRate = refreshRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.pixel_composition
     *
     * @return the value of ledpanel.pixel_composition
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getPixelComposition() {
        return pixelComposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.pixel_composition
     *
     * @param pixelComposition the value for ledpanel.pixel_composition
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setPixelComposition(String pixelComposition) {
        this.pixelComposition = pixelComposition == null ? null : pixelComposition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.Panel_dimension
     *
     * @return the value of ledpanel.Panel_dimension
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getPanelDimension() {
        return panelDimension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.Panel_dimension
     *
     * @param panelDimension the value for ledpanel.Panel_dimension
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setPanelDimension(String panelDimension) {
        this.panelDimension = panelDimension == null ? null : panelDimension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.vertical_viewing_angle
     *
     * @return the value of ledpanel.vertical_viewing_angle
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public Float getVerticalViewingAngle() {
        return verticalViewingAngle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.vertical_viewing_angle
     *
     * @param verticalViewingAngle the value for ledpanel.vertical_viewing_angle
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setVerticalViewingAngle(Float verticalViewingAngle) {
        this.verticalViewingAngle = verticalViewingAngle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.horizontal_viewing_angle
     *
     * @return the value of ledpanel.horizontal_viewing_angle
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public Float getHorizontalViewingAngle() {
        return horizontalViewingAngle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.horizontal_viewing_angle
     *
     * @param horizontalViewingAngle the value for ledpanel.horizontal_viewing_angle
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setHorizontalViewingAngle(Float horizontalViewingAngle) {
        this.horizontalViewingAngle = horizontalViewingAngle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.panel_weight
     *
     * @return the value of ledpanel.panel_weight
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public Float getPanelWeight() {
        return panelWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.panel_weight
     *
     * @param panelWeight the value for ledpanel.panel_weight
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setPanelWeight(Float panelWeight) {
        this.panelWeight = panelWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.application
     *
     * @return the value of ledpanel.application
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getApplication() {
        return application;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.application
     *
     * @param application the value for ledpanel.application
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setApplication(String application) {
        this.application = application == null ? null : application.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.ip_rating
     *
     * @return the value of ledpanel.ip_rating
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getIpRating() {
        return ipRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.ip_rating
     *
     * @param ipRating the value for ledpanel.ip_rating
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setIpRating(String ipRating) {
        this.ipRating = ipRating == null ? null : ipRating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.Gray_scale
     *
     * @return the value of ledpanel.Gray_scale
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public Integer getGrayScale() {
        return grayScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.Gray_scale
     *
     * @param grayScale the value for ledpanel.Gray_scale
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setGrayScale(Integer grayScale) {
        this.grayScale = grayScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.Panel_w_resolution
     *
     * @return the value of ledpanel.Panel_w_resolution
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getPanelWResolution() {
        return panelWResolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.Panel_w_resolution
     *
     * @param panelWResolution the value for ledpanel.Panel_w_resolution
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setPanelWResolution(String panelWResolution) {
        this.panelWResolution = panelWResolution == null ? null : panelWResolution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.Panel_h_resolution
     *
     * @return the value of ledpanel.Panel_h_resolution
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getPanelHResolution() {
        return panelHResolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.Panel_h_resolution
     *
     * @param panelHResolution the value for ledpanel.Panel_h_resolution
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setPanelHResolution(String panelHResolution) {
        this.panelHResolution = panelHResolution == null ? null : panelHResolution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.panel_resolution
     *
     * @return the value of ledpanel.panel_resolution
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getPanelResolution() {
        return panelResolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.panel_resolution
     *
     * @param panelResolution the value for ledpanel.panel_resolution
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setPanelResolution(String panelResolution) {
        this.panelResolution = panelResolution == null ? null : panelResolution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.Tile_dimension
     *
     * @return the value of ledpanel.Tile_dimension
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getTileDimension() {
        return tileDimension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.Tile_dimension
     *
     * @param tileDimension the value for ledpanel.Tile_dimension
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setTileDimension(String tileDimension) {
        this.tileDimension = tileDimension == null ? null : tileDimension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.tile_weight
     *
     * @return the value of ledpanel.tile_weight
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public Float getTileWeight() {
        return tileWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.tile_weight
     *
     * @param tileWeight the value for ledpanel.tile_weight
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setTileWeight(Float tileWeight) {
        this.tileWeight = tileWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.tile_w_resolution
     *
     * @return the value of ledpanel.tile_w_resolution
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public Integer getTileWResolution() {
        return tileWResolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.tile_w_resolution
     *
     * @param tileWResolution the value for ledpanel.tile_w_resolution
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setTileWResolution(Integer tileWResolution) {
        this.tileWResolution = tileWResolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.tile_h_resolution
     *
     * @return the value of ledpanel.tile_h_resolution
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public Integer getTileHResolution() {
        return tileHResolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.tile_h_resolution
     *
     * @param tileHResolution the value for ledpanel.tile_h_resolution
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setTileHResolution(Integer tileHResolution) {
        this.tileHResolution = tileHResolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.Panel_material
     *
     * @return the value of ledpanel.Panel_material
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getPanelMaterial() {
        return panelMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.Panel_material
     *
     * @param panelMaterial the value for ledpanel.Panel_material
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setPanelMaterial(String panelMaterial) {
        this.panelMaterial = panelMaterial == null ? null : panelMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.panel_flatness
     *
     * @return the value of ledpanel.panel_flatness
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getPanelFlatness() {
        return panelFlatness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.panel_flatness
     *
     * @param panelFlatness the value for ledpanel.panel_flatness
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setPanelFlatness(String panelFlatness) {
        this.panelFlatness = panelFlatness == null ? null : panelFlatness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.calibration
     *
     * @return the value of ledpanel.calibration
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public Boolean getCalibration() {
        return calibration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.calibration
     *
     * @param calibration the value for ledpanel.calibration
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setCalibration(Boolean calibration) {
        this.calibration = calibration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.color_temperature
     *
     * @return the value of ledpanel.color_temperature
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getColorTemperature() {
        return colorTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.color_temperature
     *
     * @param colorTemperature the value for ledpanel.color_temperature
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setColorTemperature(String colorTemperature) {
        this.colorTemperature = colorTemperature == null ? null : colorTemperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.contrast
     *
     * @return the value of ledpanel.contrast
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getContrast() {
        return contrast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.contrast
     *
     * @param contrast the value for ledpanel.contrast
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setContrast(String contrast) {
        this.contrast = contrast == null ? null : contrast.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.Power_consumption
     *
     * @return the value of ledpanel.Power_consumption
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public Float getPowerConsumption() {
        return powerConsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.Power_consumption
     *
     * @param powerConsumption the value for ledpanel.Power_consumption
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setPowerConsumption(Float powerConsumption) {
        this.powerConsumption = powerConsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.maintenance
     *
     * @return the value of ledpanel.maintenance
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getMaintenance() {
        return maintenance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.maintenance
     *
     * @param maintenance the value for ledpanel.maintenance
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setMaintenance(String maintenance) {
        this.maintenance = maintenance == null ? null : maintenance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.certification
     *
     * @return the value of ledpanel.certification
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getCertification() {
        return certification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.certification
     *
     * @param certification the value for ledpanel.certification
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setCertification(String certification) {
        this.certification = certification == null ? null : certification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.created_date
     *
     * @return the value of ledpanel.created_date
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.created_date
     *
     * @param createdDate the value for ledpanel.created_date
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.last_updated
     *
     * @return the value of ledpanel.last_updated
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.last_updated
     *
     * @param lastUpdated the value for ledpanel.last_updated
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.product_link
     *
     * @return the value of ledpanel.product_link
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getProductLink() {
        return productLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.product_link
     *
     * @param productLink the value for ledpanel.product_link
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setProductLink(String productLink) {
        this.productLink = productLink == null ? null : productLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.Operating_temperature
     *
     * @return the value of ledpanel.Operating_temperature
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getOperatingTemperature() {
        return operatingTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.Operating_temperature
     *
     * @param operatingTemperature the value for ledpanel.Operating_temperature
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setOperatingTemperature(String operatingTemperature) {
        this.operatingTemperature = operatingTemperature == null ? null : operatingTemperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.operating_RH
     *
     * @return the value of ledpanel.operating_RH
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getOperatingRh() {
        return operatingRh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.operating_RH
     *
     * @param operatingRh the value for ledpanel.operating_RH
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setOperatingRh(String operatingRh) {
        this.operatingRh = operatingRh == null ? null : operatingRh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.others
     *
     * @return the value of ledpanel.others
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.others
     *
     * @param others the value for ledpanel.others
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledpanel.picture
     *
     * @return the value of ledpanel.picture
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledpanel.picture
     *
     * @param picture the value for ledpanel.picture
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }
}