package com.hu.parser.ledparser.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LedPanelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public LedPanelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNull() {
            addCriterion("company is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNotNull() {
            addCriterion("company is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyEqualTo(String value) {
            addCriterion("company =", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotEqualTo(String value) {
            addCriterion("company <>", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThan(String value) {
            addCriterion("company >", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("company >=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThan(String value) {
            addCriterion("company <", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThanOrEqualTo(String value) {
            addCriterion("company <=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLike(String value) {
            addCriterion("company like", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotLike(String value) {
            addCriterion("company not like", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyIn(List<String> values) {
            addCriterion("company in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotIn(List<String> values) {
            addCriterion("company not in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyBetween(String value1, String value2) {
            addCriterion("company between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotBetween(String value1, String value2) {
            addCriterion("company not between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andModelIsNull() {
            addCriterion("model is null");
            return (Criteria) this;
        }

        public Criteria andModelIsNotNull() {
            addCriterion("model is not null");
            return (Criteria) this;
        }

        public Criteria andModelEqualTo(String value) {
            addCriterion("model =", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotEqualTo(String value) {
            addCriterion("model <>", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelGreaterThan(String value) {
            addCriterion("model >", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelGreaterThanOrEqualTo(String value) {
            addCriterion("model >=", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLessThan(String value) {
            addCriterion("model <", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLessThanOrEqualTo(String value) {
            addCriterion("model <=", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLike(String value) {
            addCriterion("model like", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotLike(String value) {
            addCriterion("model not like", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelIn(List<String> values) {
            addCriterion("model in", values, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotIn(List<String> values) {
            addCriterion("model not in", values, "model");
            return (Criteria) this;
        }

        public Criteria andModelBetween(String value1, String value2) {
            addCriterion("model between", value1, value2, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotBetween(String value1, String value2) {
            addCriterion("model not between", value1, value2, "model");
            return (Criteria) this;
        }

        public Criteria andPitchIsNull() {
            addCriterion("pitch is null");
            return (Criteria) this;
        }

        public Criteria andPitchIsNotNull() {
            addCriterion("pitch is not null");
            return (Criteria) this;
        }

        public Criteria andPitchEqualTo(Float value) {
            addCriterion("pitch =", value, "pitch");
            return (Criteria) this;
        }

        public Criteria andPitchNotEqualTo(Float value) {
            addCriterion("pitch <>", value, "pitch");
            return (Criteria) this;
        }

        public Criteria andPitchGreaterThan(Float value) {
            addCriterion("pitch >", value, "pitch");
            return (Criteria) this;
        }

        public Criteria andPitchGreaterThanOrEqualTo(Float value) {
            addCriterion("pitch >=", value, "pitch");
            return (Criteria) this;
        }

        public Criteria andPitchLessThan(Float value) {
            addCriterion("pitch <", value, "pitch");
            return (Criteria) this;
        }

        public Criteria andPitchLessThanOrEqualTo(Float value) {
            addCriterion("pitch <=", value, "pitch");
            return (Criteria) this;
        }

        public Criteria andPitchIn(List<Float> values) {
            addCriterion("pitch in", values, "pitch");
            return (Criteria) this;
        }

        public Criteria andPitchNotIn(List<Float> values) {
            addCriterion("pitch not in", values, "pitch");
            return (Criteria) this;
        }

        public Criteria andPitchBetween(Float value1, Float value2) {
            addCriterion("pitch between", value1, value2, "pitch");
            return (Criteria) this;
        }

        public Criteria andPitchNotBetween(Float value1, Float value2) {
            addCriterion("pitch not between", value1, value2, "pitch");
            return (Criteria) this;
        }

        public Criteria andBrightnessIsNull() {
            addCriterion("brightness is null");
            return (Criteria) this;
        }

        public Criteria andBrightnessIsNotNull() {
            addCriterion("brightness is not null");
            return (Criteria) this;
        }

        public Criteria andBrightnessEqualTo(Float value) {
            addCriterion("brightness =", value, "brightness");
            return (Criteria) this;
        }

        public Criteria andBrightnessNotEqualTo(Float value) {
            addCriterion("brightness <>", value, "brightness");
            return (Criteria) this;
        }

        public Criteria andBrightnessGreaterThan(Float value) {
            addCriterion("brightness >", value, "brightness");
            return (Criteria) this;
        }

        public Criteria andBrightnessGreaterThanOrEqualTo(Float value) {
            addCriterion("brightness >=", value, "brightness");
            return (Criteria) this;
        }

        public Criteria andBrightnessLessThan(Float value) {
            addCriterion("brightness <", value, "brightness");
            return (Criteria) this;
        }

        public Criteria andBrightnessLessThanOrEqualTo(Float value) {
            addCriterion("brightness <=", value, "brightness");
            return (Criteria) this;
        }

        public Criteria andBrightnessIn(List<Float> values) {
            addCriterion("brightness in", values, "brightness");
            return (Criteria) this;
        }

        public Criteria andBrightnessNotIn(List<Float> values) {
            addCriterion("brightness not in", values, "brightness");
            return (Criteria) this;
        }

        public Criteria andBrightnessBetween(Float value1, Float value2) {
            addCriterion("brightness between", value1, value2, "brightness");
            return (Criteria) this;
        }

        public Criteria andBrightnessNotBetween(Float value1, Float value2) {
            addCriterion("brightness not between", value1, value2, "brightness");
            return (Criteria) this;
        }

        public Criteria andRefreshRateIsNull() {
            addCriterion("refresh_rate is null");
            return (Criteria) this;
        }

        public Criteria andRefreshRateIsNotNull() {
            addCriterion("refresh_rate is not null");
            return (Criteria) this;
        }

        public Criteria andRefreshRateEqualTo(Integer value) {
            addCriterion("refresh_rate =", value, "refreshRate");
            return (Criteria) this;
        }

        public Criteria andRefreshRateNotEqualTo(Integer value) {
            addCriterion("refresh_rate <>", value, "refreshRate");
            return (Criteria) this;
        }

        public Criteria andRefreshRateGreaterThan(Integer value) {
            addCriterion("refresh_rate >", value, "refreshRate");
            return (Criteria) this;
        }

        public Criteria andRefreshRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("refresh_rate >=", value, "refreshRate");
            return (Criteria) this;
        }

        public Criteria andRefreshRateLessThan(Integer value) {
            addCriterion("refresh_rate <", value, "refreshRate");
            return (Criteria) this;
        }

        public Criteria andRefreshRateLessThanOrEqualTo(Integer value) {
            addCriterion("refresh_rate <=", value, "refreshRate");
            return (Criteria) this;
        }

        public Criteria andRefreshRateIn(List<Integer> values) {
            addCriterion("refresh_rate in", values, "refreshRate");
            return (Criteria) this;
        }

        public Criteria andRefreshRateNotIn(List<Integer> values) {
            addCriterion("refresh_rate not in", values, "refreshRate");
            return (Criteria) this;
        }

        public Criteria andRefreshRateBetween(Integer value1, Integer value2) {
            addCriterion("refresh_rate between", value1, value2, "refreshRate");
            return (Criteria) this;
        }

        public Criteria andRefreshRateNotBetween(Integer value1, Integer value2) {
            addCriterion("refresh_rate not between", value1, value2, "refreshRate");
            return (Criteria) this;
        }

        public Criteria andPixelCompositionIsNull() {
            addCriterion("pixel_composition is null");
            return (Criteria) this;
        }

        public Criteria andPixelCompositionIsNotNull() {
            addCriterion("pixel_composition is not null");
            return (Criteria) this;
        }

        public Criteria andPixelCompositionEqualTo(String value) {
            addCriterion("pixel_composition =", value, "pixelComposition");
            return (Criteria) this;
        }

        public Criteria andPixelCompositionNotEqualTo(String value) {
            addCriterion("pixel_composition <>", value, "pixelComposition");
            return (Criteria) this;
        }

        public Criteria andPixelCompositionGreaterThan(String value) {
            addCriterion("pixel_composition >", value, "pixelComposition");
            return (Criteria) this;
        }

        public Criteria andPixelCompositionGreaterThanOrEqualTo(String value) {
            addCriterion("pixel_composition >=", value, "pixelComposition");
            return (Criteria) this;
        }

        public Criteria andPixelCompositionLessThan(String value) {
            addCriterion("pixel_composition <", value, "pixelComposition");
            return (Criteria) this;
        }

        public Criteria andPixelCompositionLessThanOrEqualTo(String value) {
            addCriterion("pixel_composition <=", value, "pixelComposition");
            return (Criteria) this;
        }

        public Criteria andPixelCompositionLike(String value) {
            addCriterion("pixel_composition like", value, "pixelComposition");
            return (Criteria) this;
        }

        public Criteria andPixelCompositionNotLike(String value) {
            addCriterion("pixel_composition not like", value, "pixelComposition");
            return (Criteria) this;
        }

        public Criteria andPixelCompositionIn(List<String> values) {
            addCriterion("pixel_composition in", values, "pixelComposition");
            return (Criteria) this;
        }

        public Criteria andPixelCompositionNotIn(List<String> values) {
            addCriterion("pixel_composition not in", values, "pixelComposition");
            return (Criteria) this;
        }

        public Criteria andPixelCompositionBetween(String value1, String value2) {
            addCriterion("pixel_composition between", value1, value2, "pixelComposition");
            return (Criteria) this;
        }

        public Criteria andPixelCompositionNotBetween(String value1, String value2) {
            addCriterion("pixel_composition not between", value1, value2, "pixelComposition");
            return (Criteria) this;
        }

        public Criteria andPanelDimensionIsNull() {
            addCriterion("Panel_dimension is null");
            return (Criteria) this;
        }

        public Criteria andPanelDimensionIsNotNull() {
            addCriterion("Panel_dimension is not null");
            return (Criteria) this;
        }

        public Criteria andPanelDimensionEqualTo(String value) {
            addCriterion("Panel_dimension =", value, "panelDimension");
            return (Criteria) this;
        }

        public Criteria andPanelDimensionNotEqualTo(String value) {
            addCriterion("Panel_dimension <>", value, "panelDimension");
            return (Criteria) this;
        }

        public Criteria andPanelDimensionGreaterThan(String value) {
            addCriterion("Panel_dimension >", value, "panelDimension");
            return (Criteria) this;
        }

        public Criteria andPanelDimensionGreaterThanOrEqualTo(String value) {
            addCriterion("Panel_dimension >=", value, "panelDimension");
            return (Criteria) this;
        }

        public Criteria andPanelDimensionLessThan(String value) {
            addCriterion("Panel_dimension <", value, "panelDimension");
            return (Criteria) this;
        }

        public Criteria andPanelDimensionLessThanOrEqualTo(String value) {
            addCriterion("Panel_dimension <=", value, "panelDimension");
            return (Criteria) this;
        }

        public Criteria andPanelDimensionLike(String value) {
            addCriterion("Panel_dimension like", value, "panelDimension");
            return (Criteria) this;
        }

        public Criteria andPanelDimensionNotLike(String value) {
            addCriterion("Panel_dimension not like", value, "panelDimension");
            return (Criteria) this;
        }

        public Criteria andPanelDimensionIn(List<String> values) {
            addCriterion("Panel_dimension in", values, "panelDimension");
            return (Criteria) this;
        }

        public Criteria andPanelDimensionNotIn(List<String> values) {
            addCriterion("Panel_dimension not in", values, "panelDimension");
            return (Criteria) this;
        }

        public Criteria andPanelDimensionBetween(String value1, String value2) {
            addCriterion("Panel_dimension between", value1, value2, "panelDimension");
            return (Criteria) this;
        }

        public Criteria andPanelDimensionNotBetween(String value1, String value2) {
            addCriterion("Panel_dimension not between", value1, value2, "panelDimension");
            return (Criteria) this;
        }

        public Criteria andVerticalViewingAngleIsNull() {
            addCriterion("vertical_viewing_angle is null");
            return (Criteria) this;
        }

        public Criteria andVerticalViewingAngleIsNotNull() {
            addCriterion("vertical_viewing_angle is not null");
            return (Criteria) this;
        }

        public Criteria andVerticalViewingAngleEqualTo(Float value) {
            addCriterion("vertical_viewing_angle =", value, "verticalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andVerticalViewingAngleNotEqualTo(Float value) {
            addCriterion("vertical_viewing_angle <>", value, "verticalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andVerticalViewingAngleGreaterThan(Float value) {
            addCriterion("vertical_viewing_angle >", value, "verticalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andVerticalViewingAngleGreaterThanOrEqualTo(Float value) {
            addCriterion("vertical_viewing_angle >=", value, "verticalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andVerticalViewingAngleLessThan(Float value) {
            addCriterion("vertical_viewing_angle <", value, "verticalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andVerticalViewingAngleLessThanOrEqualTo(Float value) {
            addCriterion("vertical_viewing_angle <=", value, "verticalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andVerticalViewingAngleIn(List<Float> values) {
            addCriterion("vertical_viewing_angle in", values, "verticalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andVerticalViewingAngleNotIn(List<Float> values) {
            addCriterion("vertical_viewing_angle not in", values, "verticalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andVerticalViewingAngleBetween(Float value1, Float value2) {
            addCriterion("vertical_viewing_angle between", value1, value2, "verticalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andVerticalViewingAngleNotBetween(Float value1, Float value2) {
            addCriterion("vertical_viewing_angle not between", value1, value2, "verticalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andHorizontalViewingAngleIsNull() {
            addCriterion("horizontal_viewing_angle is null");
            return (Criteria) this;
        }

        public Criteria andHorizontalViewingAngleIsNotNull() {
            addCriterion("horizontal_viewing_angle is not null");
            return (Criteria) this;
        }

        public Criteria andHorizontalViewingAngleEqualTo(Float value) {
            addCriterion("horizontal_viewing_angle =", value, "horizontalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andHorizontalViewingAngleNotEqualTo(Float value) {
            addCriterion("horizontal_viewing_angle <>", value, "horizontalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andHorizontalViewingAngleGreaterThan(Float value) {
            addCriterion("horizontal_viewing_angle >", value, "horizontalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andHorizontalViewingAngleGreaterThanOrEqualTo(Float value) {
            addCriterion("horizontal_viewing_angle >=", value, "horizontalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andHorizontalViewingAngleLessThan(Float value) {
            addCriterion("horizontal_viewing_angle <", value, "horizontalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andHorizontalViewingAngleLessThanOrEqualTo(Float value) {
            addCriterion("horizontal_viewing_angle <=", value, "horizontalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andHorizontalViewingAngleIn(List<Float> values) {
            addCriterion("horizontal_viewing_angle in", values, "horizontalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andHorizontalViewingAngleNotIn(List<Float> values) {
            addCriterion("horizontal_viewing_angle not in", values, "horizontalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andHorizontalViewingAngleBetween(Float value1, Float value2) {
            addCriterion("horizontal_viewing_angle between", value1, value2, "horizontalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andHorizontalViewingAngleNotBetween(Float value1, Float value2) {
            addCriterion("horizontal_viewing_angle not between", value1, value2, "horizontalViewingAngle");
            return (Criteria) this;
        }

        public Criteria andPanelWeightIsNull() {
            addCriterion("panel_weight is null");
            return (Criteria) this;
        }

        public Criteria andPanelWeightIsNotNull() {
            addCriterion("panel_weight is not null");
            return (Criteria) this;
        }

        public Criteria andPanelWeightEqualTo(Float value) {
            addCriterion("panel_weight =", value, "panelWeight");
            return (Criteria) this;
        }

        public Criteria andPanelWeightNotEqualTo(Float value) {
            addCriterion("panel_weight <>", value, "panelWeight");
            return (Criteria) this;
        }

        public Criteria andPanelWeightGreaterThan(Float value) {
            addCriterion("panel_weight >", value, "panelWeight");
            return (Criteria) this;
        }

        public Criteria andPanelWeightGreaterThanOrEqualTo(Float value) {
            addCriterion("panel_weight >=", value, "panelWeight");
            return (Criteria) this;
        }

        public Criteria andPanelWeightLessThan(Float value) {
            addCriterion("panel_weight <", value, "panelWeight");
            return (Criteria) this;
        }

        public Criteria andPanelWeightLessThanOrEqualTo(Float value) {
            addCriterion("panel_weight <=", value, "panelWeight");
            return (Criteria) this;
        }

        public Criteria andPanelWeightIn(List<Float> values) {
            addCriterion("panel_weight in", values, "panelWeight");
            return (Criteria) this;
        }

        public Criteria andPanelWeightNotIn(List<Float> values) {
            addCriterion("panel_weight not in", values, "panelWeight");
            return (Criteria) this;
        }

        public Criteria andPanelWeightBetween(Float value1, Float value2) {
            addCriterion("panel_weight between", value1, value2, "panelWeight");
            return (Criteria) this;
        }

        public Criteria andPanelWeightNotBetween(Float value1, Float value2) {
            addCriterion("panel_weight not between", value1, value2, "panelWeight");
            return (Criteria) this;
        }

        public Criteria andApplicationIsNull() {
            addCriterion("application is null");
            return (Criteria) this;
        }

        public Criteria andApplicationIsNotNull() {
            addCriterion("application is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationEqualTo(String value) {
            addCriterion("application =", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationNotEqualTo(String value) {
            addCriterion("application <>", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationGreaterThan(String value) {
            addCriterion("application >", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationGreaterThanOrEqualTo(String value) {
            addCriterion("application >=", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationLessThan(String value) {
            addCriterion("application <", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationLessThanOrEqualTo(String value) {
            addCriterion("application <=", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationLike(String value) {
            addCriterion("application like", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationNotLike(String value) {
            addCriterion("application not like", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationIn(List<String> values) {
            addCriterion("application in", values, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationNotIn(List<String> values) {
            addCriterion("application not in", values, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationBetween(String value1, String value2) {
            addCriterion("application between", value1, value2, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationNotBetween(String value1, String value2) {
            addCriterion("application not between", value1, value2, "application");
            return (Criteria) this;
        }

        public Criteria andIpRatingIsNull() {
            addCriterion("ip_rating is null");
            return (Criteria) this;
        }

        public Criteria andIpRatingIsNotNull() {
            addCriterion("ip_rating is not null");
            return (Criteria) this;
        }

        public Criteria andIpRatingEqualTo(String value) {
            addCriterion("ip_rating =", value, "ipRating");
            return (Criteria) this;
        }

        public Criteria andIpRatingNotEqualTo(String value) {
            addCriterion("ip_rating <>", value, "ipRating");
            return (Criteria) this;
        }

        public Criteria andIpRatingGreaterThan(String value) {
            addCriterion("ip_rating >", value, "ipRating");
            return (Criteria) this;
        }

        public Criteria andIpRatingGreaterThanOrEqualTo(String value) {
            addCriterion("ip_rating >=", value, "ipRating");
            return (Criteria) this;
        }

        public Criteria andIpRatingLessThan(String value) {
            addCriterion("ip_rating <", value, "ipRating");
            return (Criteria) this;
        }

        public Criteria andIpRatingLessThanOrEqualTo(String value) {
            addCriterion("ip_rating <=", value, "ipRating");
            return (Criteria) this;
        }

        public Criteria andIpRatingLike(String value) {
            addCriterion("ip_rating like", value, "ipRating");
            return (Criteria) this;
        }

        public Criteria andIpRatingNotLike(String value) {
            addCriterion("ip_rating not like", value, "ipRating");
            return (Criteria) this;
        }

        public Criteria andIpRatingIn(List<String> values) {
            addCriterion("ip_rating in", values, "ipRating");
            return (Criteria) this;
        }

        public Criteria andIpRatingNotIn(List<String> values) {
            addCriterion("ip_rating not in", values, "ipRating");
            return (Criteria) this;
        }

        public Criteria andIpRatingBetween(String value1, String value2) {
            addCriterion("ip_rating between", value1, value2, "ipRating");
            return (Criteria) this;
        }

        public Criteria andIpRatingNotBetween(String value1, String value2) {
            addCriterion("ip_rating not between", value1, value2, "ipRating");
            return (Criteria) this;
        }

        public Criteria andGrayScaleIsNull() {
            addCriterion("Gray_scale is null");
            return (Criteria) this;
        }

        public Criteria andGrayScaleIsNotNull() {
            addCriterion("Gray_scale is not null");
            return (Criteria) this;
        }

        public Criteria andGrayScaleEqualTo(Integer value) {
            addCriterion("Gray_scale =", value, "grayScale");
            return (Criteria) this;
        }

        public Criteria andGrayScaleNotEqualTo(Integer value) {
            addCriterion("Gray_scale <>", value, "grayScale");
            return (Criteria) this;
        }

        public Criteria andGrayScaleGreaterThan(Integer value) {
            addCriterion("Gray_scale >", value, "grayScale");
            return (Criteria) this;
        }

        public Criteria andGrayScaleGreaterThanOrEqualTo(Integer value) {
            addCriterion("Gray_scale >=", value, "grayScale");
            return (Criteria) this;
        }

        public Criteria andGrayScaleLessThan(Integer value) {
            addCriterion("Gray_scale <", value, "grayScale");
            return (Criteria) this;
        }

        public Criteria andGrayScaleLessThanOrEqualTo(Integer value) {
            addCriterion("Gray_scale <=", value, "grayScale");
            return (Criteria) this;
        }

        public Criteria andGrayScaleIn(List<Integer> values) {
            addCriterion("Gray_scale in", values, "grayScale");
            return (Criteria) this;
        }

        public Criteria andGrayScaleNotIn(List<Integer> values) {
            addCriterion("Gray_scale not in", values, "grayScale");
            return (Criteria) this;
        }

        public Criteria andGrayScaleBetween(Integer value1, Integer value2) {
            addCriterion("Gray_scale between", value1, value2, "grayScale");
            return (Criteria) this;
        }

        public Criteria andGrayScaleNotBetween(Integer value1, Integer value2) {
            addCriterion("Gray_scale not between", value1, value2, "grayScale");
            return (Criteria) this;
        }

        public Criteria andPanelWResolutionIsNull() {
            addCriterion("Panel_w_resolution is null");
            return (Criteria) this;
        }

        public Criteria andPanelWResolutionIsNotNull() {
            addCriterion("Panel_w_resolution is not null");
            return (Criteria) this;
        }

        public Criteria andPanelWResolutionEqualTo(String value) {
            addCriterion("Panel_w_resolution =", value, "panelWResolution");
            return (Criteria) this;
        }

        public Criteria andPanelWResolutionNotEqualTo(String value) {
            addCriterion("Panel_w_resolution <>", value, "panelWResolution");
            return (Criteria) this;
        }

        public Criteria andPanelWResolutionGreaterThan(String value) {
            addCriterion("Panel_w_resolution >", value, "panelWResolution");
            return (Criteria) this;
        }

        public Criteria andPanelWResolutionGreaterThanOrEqualTo(String value) {
            addCriterion("Panel_w_resolution >=", value, "panelWResolution");
            return (Criteria) this;
        }

        public Criteria andPanelWResolutionLessThan(String value) {
            addCriterion("Panel_w_resolution <", value, "panelWResolution");
            return (Criteria) this;
        }

        public Criteria andPanelWResolutionLessThanOrEqualTo(String value) {
            addCriterion("Panel_w_resolution <=", value, "panelWResolution");
            return (Criteria) this;
        }

        public Criteria andPanelWResolutionLike(String value) {
            addCriterion("Panel_w_resolution like", value, "panelWResolution");
            return (Criteria) this;
        }

        public Criteria andPanelWResolutionNotLike(String value) {
            addCriterion("Panel_w_resolution not like", value, "panelWResolution");
            return (Criteria) this;
        }

        public Criteria andPanelWResolutionIn(List<String> values) {
            addCriterion("Panel_w_resolution in", values, "panelWResolution");
            return (Criteria) this;
        }

        public Criteria andPanelWResolutionNotIn(List<String> values) {
            addCriterion("Panel_w_resolution not in", values, "panelWResolution");
            return (Criteria) this;
        }

        public Criteria andPanelWResolutionBetween(String value1, String value2) {
            addCriterion("Panel_w_resolution between", value1, value2, "panelWResolution");
            return (Criteria) this;
        }

        public Criteria andPanelWResolutionNotBetween(String value1, String value2) {
            addCriterion("Panel_w_resolution not between", value1, value2, "panelWResolution");
            return (Criteria) this;
        }

        public Criteria andPanelHResolutionIsNull() {
            addCriterion("Panel_h_resolution is null");
            return (Criteria) this;
        }

        public Criteria andPanelHResolutionIsNotNull() {
            addCriterion("Panel_h_resolution is not null");
            return (Criteria) this;
        }

        public Criteria andPanelHResolutionEqualTo(String value) {
            addCriterion("Panel_h_resolution =", value, "panelHResolution");
            return (Criteria) this;
        }

        public Criteria andPanelHResolutionNotEqualTo(String value) {
            addCriterion("Panel_h_resolution <>", value, "panelHResolution");
            return (Criteria) this;
        }

        public Criteria andPanelHResolutionGreaterThan(String value) {
            addCriterion("Panel_h_resolution >", value, "panelHResolution");
            return (Criteria) this;
        }

        public Criteria andPanelHResolutionGreaterThanOrEqualTo(String value) {
            addCriterion("Panel_h_resolution >=", value, "panelHResolution");
            return (Criteria) this;
        }

        public Criteria andPanelHResolutionLessThan(String value) {
            addCriterion("Panel_h_resolution <", value, "panelHResolution");
            return (Criteria) this;
        }

        public Criteria andPanelHResolutionLessThanOrEqualTo(String value) {
            addCriterion("Panel_h_resolution <=", value, "panelHResolution");
            return (Criteria) this;
        }

        public Criteria andPanelHResolutionLike(String value) {
            addCriterion("Panel_h_resolution like", value, "panelHResolution");
            return (Criteria) this;
        }

        public Criteria andPanelHResolutionNotLike(String value) {
            addCriterion("Panel_h_resolution not like", value, "panelHResolution");
            return (Criteria) this;
        }

        public Criteria andPanelHResolutionIn(List<String> values) {
            addCriterion("Panel_h_resolution in", values, "panelHResolution");
            return (Criteria) this;
        }

        public Criteria andPanelHResolutionNotIn(List<String> values) {
            addCriterion("Panel_h_resolution not in", values, "panelHResolution");
            return (Criteria) this;
        }

        public Criteria andPanelHResolutionBetween(String value1, String value2) {
            addCriterion("Panel_h_resolution between", value1, value2, "panelHResolution");
            return (Criteria) this;
        }

        public Criteria andPanelHResolutionNotBetween(String value1, String value2) {
            addCriterion("Panel_h_resolution not between", value1, value2, "panelHResolution");
            return (Criteria) this;
        }

        public Criteria andPanelResolutionIsNull() {
            addCriterion("panel_resolution is null");
            return (Criteria) this;
        }

        public Criteria andPanelResolutionIsNotNull() {
            addCriterion("panel_resolution is not null");
            return (Criteria) this;
        }

        public Criteria andPanelResolutionEqualTo(String value) {
            addCriterion("panel_resolution =", value, "panelResolution");
            return (Criteria) this;
        }

        public Criteria andPanelResolutionNotEqualTo(String value) {
            addCriterion("panel_resolution <>", value, "panelResolution");
            return (Criteria) this;
        }

        public Criteria andPanelResolutionGreaterThan(String value) {
            addCriterion("panel_resolution >", value, "panelResolution");
            return (Criteria) this;
        }

        public Criteria andPanelResolutionGreaterThanOrEqualTo(String value) {
            addCriterion("panel_resolution >=", value, "panelResolution");
            return (Criteria) this;
        }

        public Criteria andPanelResolutionLessThan(String value) {
            addCriterion("panel_resolution <", value, "panelResolution");
            return (Criteria) this;
        }

        public Criteria andPanelResolutionLessThanOrEqualTo(String value) {
            addCriterion("panel_resolution <=", value, "panelResolution");
            return (Criteria) this;
        }

        public Criteria andPanelResolutionLike(String value) {
            addCriterion("panel_resolution like", value, "panelResolution");
            return (Criteria) this;
        }

        public Criteria andPanelResolutionNotLike(String value) {
            addCriterion("panel_resolution not like", value, "panelResolution");
            return (Criteria) this;
        }

        public Criteria andPanelResolutionIn(List<String> values) {
            addCriterion("panel_resolution in", values, "panelResolution");
            return (Criteria) this;
        }

        public Criteria andPanelResolutionNotIn(List<String> values) {
            addCriterion("panel_resolution not in", values, "panelResolution");
            return (Criteria) this;
        }

        public Criteria andPanelResolutionBetween(String value1, String value2) {
            addCriterion("panel_resolution between", value1, value2, "panelResolution");
            return (Criteria) this;
        }

        public Criteria andPanelResolutionNotBetween(String value1, String value2) {
            addCriterion("panel_resolution not between", value1, value2, "panelResolution");
            return (Criteria) this;
        }

        public Criteria andTileDimensionIsNull() {
            addCriterion("Tile_dimension is null");
            return (Criteria) this;
        }

        public Criteria andTileDimensionIsNotNull() {
            addCriterion("Tile_dimension is not null");
            return (Criteria) this;
        }

        public Criteria andTileDimensionEqualTo(String value) {
            addCriterion("Tile_dimension =", value, "tileDimension");
            return (Criteria) this;
        }

        public Criteria andTileDimensionNotEqualTo(String value) {
            addCriterion("Tile_dimension <>", value, "tileDimension");
            return (Criteria) this;
        }

        public Criteria andTileDimensionGreaterThan(String value) {
            addCriterion("Tile_dimension >", value, "tileDimension");
            return (Criteria) this;
        }

        public Criteria andTileDimensionGreaterThanOrEqualTo(String value) {
            addCriterion("Tile_dimension >=", value, "tileDimension");
            return (Criteria) this;
        }

        public Criteria andTileDimensionLessThan(String value) {
            addCriterion("Tile_dimension <", value, "tileDimension");
            return (Criteria) this;
        }

        public Criteria andTileDimensionLessThanOrEqualTo(String value) {
            addCriterion("Tile_dimension <=", value, "tileDimension");
            return (Criteria) this;
        }

        public Criteria andTileDimensionLike(String value) {
            addCriterion("Tile_dimension like", value, "tileDimension");
            return (Criteria) this;
        }

        public Criteria andTileDimensionNotLike(String value) {
            addCriterion("Tile_dimension not like", value, "tileDimension");
            return (Criteria) this;
        }

        public Criteria andTileDimensionIn(List<String> values) {
            addCriterion("Tile_dimension in", values, "tileDimension");
            return (Criteria) this;
        }

        public Criteria andTileDimensionNotIn(List<String> values) {
            addCriterion("Tile_dimension not in", values, "tileDimension");
            return (Criteria) this;
        }

        public Criteria andTileDimensionBetween(String value1, String value2) {
            addCriterion("Tile_dimension between", value1, value2, "tileDimension");
            return (Criteria) this;
        }

        public Criteria andTileDimensionNotBetween(String value1, String value2) {
            addCriterion("Tile_dimension not between", value1, value2, "tileDimension");
            return (Criteria) this;
        }

        public Criteria andTileWeightIsNull() {
            addCriterion("tile_weight is null");
            return (Criteria) this;
        }

        public Criteria andTileWeightIsNotNull() {
            addCriterion("tile_weight is not null");
            return (Criteria) this;
        }

        public Criteria andTileWeightEqualTo(Float value) {
            addCriterion("tile_weight =", value, "tileWeight");
            return (Criteria) this;
        }

        public Criteria andTileWeightNotEqualTo(Float value) {
            addCriterion("tile_weight <>", value, "tileWeight");
            return (Criteria) this;
        }

        public Criteria andTileWeightGreaterThan(Float value) {
            addCriterion("tile_weight >", value, "tileWeight");
            return (Criteria) this;
        }

        public Criteria andTileWeightGreaterThanOrEqualTo(Float value) {
            addCriterion("tile_weight >=", value, "tileWeight");
            return (Criteria) this;
        }

        public Criteria andTileWeightLessThan(Float value) {
            addCriterion("tile_weight <", value, "tileWeight");
            return (Criteria) this;
        }

        public Criteria andTileWeightLessThanOrEqualTo(Float value) {
            addCriterion("tile_weight <=", value, "tileWeight");
            return (Criteria) this;
        }

        public Criteria andTileWeightIn(List<Float> values) {
            addCriterion("tile_weight in", values, "tileWeight");
            return (Criteria) this;
        }

        public Criteria andTileWeightNotIn(List<Float> values) {
            addCriterion("tile_weight not in", values, "tileWeight");
            return (Criteria) this;
        }

        public Criteria andTileWeightBetween(Float value1, Float value2) {
            addCriterion("tile_weight between", value1, value2, "tileWeight");
            return (Criteria) this;
        }

        public Criteria andTileWeightNotBetween(Float value1, Float value2) {
            addCriterion("tile_weight not between", value1, value2, "tileWeight");
            return (Criteria) this;
        }

        public Criteria andTileWResolutionIsNull() {
            addCriterion("tile_w_resolution is null");
            return (Criteria) this;
        }

        public Criteria andTileWResolutionIsNotNull() {
            addCriterion("tile_w_resolution is not null");
            return (Criteria) this;
        }

        public Criteria andTileWResolutionEqualTo(Integer value) {
            addCriterion("tile_w_resolution =", value, "tileWResolution");
            return (Criteria) this;
        }

        public Criteria andTileWResolutionNotEqualTo(Integer value) {
            addCriterion("tile_w_resolution <>", value, "tileWResolution");
            return (Criteria) this;
        }

        public Criteria andTileWResolutionGreaterThan(Integer value) {
            addCriterion("tile_w_resolution >", value, "tileWResolution");
            return (Criteria) this;
        }

        public Criteria andTileWResolutionGreaterThanOrEqualTo(Integer value) {
            addCriterion("tile_w_resolution >=", value, "tileWResolution");
            return (Criteria) this;
        }

        public Criteria andTileWResolutionLessThan(Integer value) {
            addCriterion("tile_w_resolution <", value, "tileWResolution");
            return (Criteria) this;
        }

        public Criteria andTileWResolutionLessThanOrEqualTo(Integer value) {
            addCriterion("tile_w_resolution <=", value, "tileWResolution");
            return (Criteria) this;
        }

        public Criteria andTileWResolutionIn(List<Integer> values) {
            addCriterion("tile_w_resolution in", values, "tileWResolution");
            return (Criteria) this;
        }

        public Criteria andTileWResolutionNotIn(List<Integer> values) {
            addCriterion("tile_w_resolution not in", values, "tileWResolution");
            return (Criteria) this;
        }

        public Criteria andTileWResolutionBetween(Integer value1, Integer value2) {
            addCriterion("tile_w_resolution between", value1, value2, "tileWResolution");
            return (Criteria) this;
        }

        public Criteria andTileWResolutionNotBetween(Integer value1, Integer value2) {
            addCriterion("tile_w_resolution not between", value1, value2, "tileWResolution");
            return (Criteria) this;
        }

        public Criteria andTileHResolutionIsNull() {
            addCriterion("tile_h_resolution is null");
            return (Criteria) this;
        }

        public Criteria andTileHResolutionIsNotNull() {
            addCriterion("tile_h_resolution is not null");
            return (Criteria) this;
        }

        public Criteria andTileHResolutionEqualTo(Integer value) {
            addCriterion("tile_h_resolution =", value, "tileHResolution");
            return (Criteria) this;
        }

        public Criteria andTileHResolutionNotEqualTo(Integer value) {
            addCriterion("tile_h_resolution <>", value, "tileHResolution");
            return (Criteria) this;
        }

        public Criteria andTileHResolutionGreaterThan(Integer value) {
            addCriterion("tile_h_resolution >", value, "tileHResolution");
            return (Criteria) this;
        }

        public Criteria andTileHResolutionGreaterThanOrEqualTo(Integer value) {
            addCriterion("tile_h_resolution >=", value, "tileHResolution");
            return (Criteria) this;
        }

        public Criteria andTileHResolutionLessThan(Integer value) {
            addCriterion("tile_h_resolution <", value, "tileHResolution");
            return (Criteria) this;
        }

        public Criteria andTileHResolutionLessThanOrEqualTo(Integer value) {
            addCriterion("tile_h_resolution <=", value, "tileHResolution");
            return (Criteria) this;
        }

        public Criteria andTileHResolutionIn(List<Integer> values) {
            addCriterion("tile_h_resolution in", values, "tileHResolution");
            return (Criteria) this;
        }

        public Criteria andTileHResolutionNotIn(List<Integer> values) {
            addCriterion("tile_h_resolution not in", values, "tileHResolution");
            return (Criteria) this;
        }

        public Criteria andTileHResolutionBetween(Integer value1, Integer value2) {
            addCriterion("tile_h_resolution between", value1, value2, "tileHResolution");
            return (Criteria) this;
        }

        public Criteria andTileHResolutionNotBetween(Integer value1, Integer value2) {
            addCriterion("tile_h_resolution not between", value1, value2, "tileHResolution");
            return (Criteria) this;
        }

        public Criteria andPanelMaterialIsNull() {
            addCriterion("Panel_material is null");
            return (Criteria) this;
        }

        public Criteria andPanelMaterialIsNotNull() {
            addCriterion("Panel_material is not null");
            return (Criteria) this;
        }

        public Criteria andPanelMaterialEqualTo(String value) {
            addCriterion("Panel_material =", value, "panelMaterial");
            return (Criteria) this;
        }

        public Criteria andPanelMaterialNotEqualTo(String value) {
            addCriterion("Panel_material <>", value, "panelMaterial");
            return (Criteria) this;
        }

        public Criteria andPanelMaterialGreaterThan(String value) {
            addCriterion("Panel_material >", value, "panelMaterial");
            return (Criteria) this;
        }

        public Criteria andPanelMaterialGreaterThanOrEqualTo(String value) {
            addCriterion("Panel_material >=", value, "panelMaterial");
            return (Criteria) this;
        }

        public Criteria andPanelMaterialLessThan(String value) {
            addCriterion("Panel_material <", value, "panelMaterial");
            return (Criteria) this;
        }

        public Criteria andPanelMaterialLessThanOrEqualTo(String value) {
            addCriterion("Panel_material <=", value, "panelMaterial");
            return (Criteria) this;
        }

        public Criteria andPanelMaterialLike(String value) {
            addCriterion("Panel_material like", value, "panelMaterial");
            return (Criteria) this;
        }

        public Criteria andPanelMaterialNotLike(String value) {
            addCriterion("Panel_material not like", value, "panelMaterial");
            return (Criteria) this;
        }

        public Criteria andPanelMaterialIn(List<String> values) {
            addCriterion("Panel_material in", values, "panelMaterial");
            return (Criteria) this;
        }

        public Criteria andPanelMaterialNotIn(List<String> values) {
            addCriterion("Panel_material not in", values, "panelMaterial");
            return (Criteria) this;
        }

        public Criteria andPanelMaterialBetween(String value1, String value2) {
            addCriterion("Panel_material between", value1, value2, "panelMaterial");
            return (Criteria) this;
        }

        public Criteria andPanelMaterialNotBetween(String value1, String value2) {
            addCriterion("Panel_material not between", value1, value2, "panelMaterial");
            return (Criteria) this;
        }

        public Criteria andPanelFlatnessIsNull() {
            addCriterion("panel_flatness is null");
            return (Criteria) this;
        }

        public Criteria andPanelFlatnessIsNotNull() {
            addCriterion("panel_flatness is not null");
            return (Criteria) this;
        }

        public Criteria andPanelFlatnessEqualTo(String value) {
            addCriterion("panel_flatness =", value, "panelFlatness");
            return (Criteria) this;
        }

        public Criteria andPanelFlatnessNotEqualTo(String value) {
            addCriterion("panel_flatness <>", value, "panelFlatness");
            return (Criteria) this;
        }

        public Criteria andPanelFlatnessGreaterThan(String value) {
            addCriterion("panel_flatness >", value, "panelFlatness");
            return (Criteria) this;
        }

        public Criteria andPanelFlatnessGreaterThanOrEqualTo(String value) {
            addCriterion("panel_flatness >=", value, "panelFlatness");
            return (Criteria) this;
        }

        public Criteria andPanelFlatnessLessThan(String value) {
            addCriterion("panel_flatness <", value, "panelFlatness");
            return (Criteria) this;
        }

        public Criteria andPanelFlatnessLessThanOrEqualTo(String value) {
            addCriterion("panel_flatness <=", value, "panelFlatness");
            return (Criteria) this;
        }

        public Criteria andPanelFlatnessLike(String value) {
            addCriterion("panel_flatness like", value, "panelFlatness");
            return (Criteria) this;
        }

        public Criteria andPanelFlatnessNotLike(String value) {
            addCriterion("panel_flatness not like", value, "panelFlatness");
            return (Criteria) this;
        }

        public Criteria andPanelFlatnessIn(List<String> values) {
            addCriterion("panel_flatness in", values, "panelFlatness");
            return (Criteria) this;
        }

        public Criteria andPanelFlatnessNotIn(List<String> values) {
            addCriterion("panel_flatness not in", values, "panelFlatness");
            return (Criteria) this;
        }

        public Criteria andPanelFlatnessBetween(String value1, String value2) {
            addCriterion("panel_flatness between", value1, value2, "panelFlatness");
            return (Criteria) this;
        }

        public Criteria andPanelFlatnessNotBetween(String value1, String value2) {
            addCriterion("panel_flatness not between", value1, value2, "panelFlatness");
            return (Criteria) this;
        }

        public Criteria andCalibrationIsNull() {
            addCriterion("calibration is null");
            return (Criteria) this;
        }

        public Criteria andCalibrationIsNotNull() {
            addCriterion("calibration is not null");
            return (Criteria) this;
        }

        public Criteria andCalibrationEqualTo(Boolean value) {
            addCriterion("calibration =", value, "calibration");
            return (Criteria) this;
        }

        public Criteria andCalibrationNotEqualTo(Boolean value) {
            addCriterion("calibration <>", value, "calibration");
            return (Criteria) this;
        }

        public Criteria andCalibrationGreaterThan(Boolean value) {
            addCriterion("calibration >", value, "calibration");
            return (Criteria) this;
        }

        public Criteria andCalibrationGreaterThanOrEqualTo(Boolean value) {
            addCriterion("calibration >=", value, "calibration");
            return (Criteria) this;
        }

        public Criteria andCalibrationLessThan(Boolean value) {
            addCriterion("calibration <", value, "calibration");
            return (Criteria) this;
        }

        public Criteria andCalibrationLessThanOrEqualTo(Boolean value) {
            addCriterion("calibration <=", value, "calibration");
            return (Criteria) this;
        }

        public Criteria andCalibrationIn(List<Boolean> values) {
            addCriterion("calibration in", values, "calibration");
            return (Criteria) this;
        }

        public Criteria andCalibrationNotIn(List<Boolean> values) {
            addCriterion("calibration not in", values, "calibration");
            return (Criteria) this;
        }

        public Criteria andCalibrationBetween(Boolean value1, Boolean value2) {
            addCriterion("calibration between", value1, value2, "calibration");
            return (Criteria) this;
        }

        public Criteria andCalibrationNotBetween(Boolean value1, Boolean value2) {
            addCriterion("calibration not between", value1, value2, "calibration");
            return (Criteria) this;
        }

        public Criteria andColorTemperatureIsNull() {
            addCriterion("color_temperature is null");
            return (Criteria) this;
        }

        public Criteria andColorTemperatureIsNotNull() {
            addCriterion("color_temperature is not null");
            return (Criteria) this;
        }

        public Criteria andColorTemperatureEqualTo(String value) {
            addCriterion("color_temperature =", value, "colorTemperature");
            return (Criteria) this;
        }

        public Criteria andColorTemperatureNotEqualTo(String value) {
            addCriterion("color_temperature <>", value, "colorTemperature");
            return (Criteria) this;
        }

        public Criteria andColorTemperatureGreaterThan(String value) {
            addCriterion("color_temperature >", value, "colorTemperature");
            return (Criteria) this;
        }

        public Criteria andColorTemperatureGreaterThanOrEqualTo(String value) {
            addCriterion("color_temperature >=", value, "colorTemperature");
            return (Criteria) this;
        }

        public Criteria andColorTemperatureLessThan(String value) {
            addCriterion("color_temperature <", value, "colorTemperature");
            return (Criteria) this;
        }

        public Criteria andColorTemperatureLessThanOrEqualTo(String value) {
            addCriterion("color_temperature <=", value, "colorTemperature");
            return (Criteria) this;
        }

        public Criteria andColorTemperatureLike(String value) {
            addCriterion("color_temperature like", value, "colorTemperature");
            return (Criteria) this;
        }

        public Criteria andColorTemperatureNotLike(String value) {
            addCriterion("color_temperature not like", value, "colorTemperature");
            return (Criteria) this;
        }

        public Criteria andColorTemperatureIn(List<String> values) {
            addCriterion("color_temperature in", values, "colorTemperature");
            return (Criteria) this;
        }

        public Criteria andColorTemperatureNotIn(List<String> values) {
            addCriterion("color_temperature not in", values, "colorTemperature");
            return (Criteria) this;
        }

        public Criteria andColorTemperatureBetween(String value1, String value2) {
            addCriterion("color_temperature between", value1, value2, "colorTemperature");
            return (Criteria) this;
        }

        public Criteria andColorTemperatureNotBetween(String value1, String value2) {
            addCriterion("color_temperature not between", value1, value2, "colorTemperature");
            return (Criteria) this;
        }

        public Criteria andContrastIsNull() {
            addCriterion("contrast is null");
            return (Criteria) this;
        }

        public Criteria andContrastIsNotNull() {
            addCriterion("contrast is not null");
            return (Criteria) this;
        }

        public Criteria andContrastEqualTo(String value) {
            addCriterion("contrast =", value, "contrast");
            return (Criteria) this;
        }

        public Criteria andContrastNotEqualTo(String value) {
            addCriterion("contrast <>", value, "contrast");
            return (Criteria) this;
        }

        public Criteria andContrastGreaterThan(String value) {
            addCriterion("contrast >", value, "contrast");
            return (Criteria) this;
        }

        public Criteria andContrastGreaterThanOrEqualTo(String value) {
            addCriterion("contrast >=", value, "contrast");
            return (Criteria) this;
        }

        public Criteria andContrastLessThan(String value) {
            addCriterion("contrast <", value, "contrast");
            return (Criteria) this;
        }

        public Criteria andContrastLessThanOrEqualTo(String value) {
            addCriterion("contrast <=", value, "contrast");
            return (Criteria) this;
        }

        public Criteria andContrastLike(String value) {
            addCriterion("contrast like", value, "contrast");
            return (Criteria) this;
        }

        public Criteria andContrastNotLike(String value) {
            addCriterion("contrast not like", value, "contrast");
            return (Criteria) this;
        }

        public Criteria andContrastIn(List<String> values) {
            addCriterion("contrast in", values, "contrast");
            return (Criteria) this;
        }

        public Criteria andContrastNotIn(List<String> values) {
            addCriterion("contrast not in", values, "contrast");
            return (Criteria) this;
        }

        public Criteria andContrastBetween(String value1, String value2) {
            addCriterion("contrast between", value1, value2, "contrast");
            return (Criteria) this;
        }

        public Criteria andContrastNotBetween(String value1, String value2) {
            addCriterion("contrast not between", value1, value2, "contrast");
            return (Criteria) this;
        }

        public Criteria andPowerConsumptionIsNull() {
            addCriterion("Power_consumption is null");
            return (Criteria) this;
        }

        public Criteria andPowerConsumptionIsNotNull() {
            addCriterion("Power_consumption is not null");
            return (Criteria) this;
        }

        public Criteria andPowerConsumptionEqualTo(Float value) {
            addCriterion("Power_consumption =", value, "powerConsumption");
            return (Criteria) this;
        }

        public Criteria andPowerConsumptionNotEqualTo(Float value) {
            addCriterion("Power_consumption <>", value, "powerConsumption");
            return (Criteria) this;
        }

        public Criteria andPowerConsumptionGreaterThan(Float value) {
            addCriterion("Power_consumption >", value, "powerConsumption");
            return (Criteria) this;
        }

        public Criteria andPowerConsumptionGreaterThanOrEqualTo(Float value) {
            addCriterion("Power_consumption >=", value, "powerConsumption");
            return (Criteria) this;
        }

        public Criteria andPowerConsumptionLessThan(Float value) {
            addCriterion("Power_consumption <", value, "powerConsumption");
            return (Criteria) this;
        }

        public Criteria andPowerConsumptionLessThanOrEqualTo(Float value) {
            addCriterion("Power_consumption <=", value, "powerConsumption");
            return (Criteria) this;
        }

        public Criteria andPowerConsumptionIn(List<Float> values) {
            addCriterion("Power_consumption in", values, "powerConsumption");
            return (Criteria) this;
        }

        public Criteria andPowerConsumptionNotIn(List<Float> values) {
            addCriterion("Power_consumption not in", values, "powerConsumption");
            return (Criteria) this;
        }

        public Criteria andPowerConsumptionBetween(Float value1, Float value2) {
            addCriterion("Power_consumption between", value1, value2, "powerConsumption");
            return (Criteria) this;
        }

        public Criteria andPowerConsumptionNotBetween(Float value1, Float value2) {
            addCriterion("Power_consumption not between", value1, value2, "powerConsumption");
            return (Criteria) this;
        }

        public Criteria andMaintenanceIsNull() {
            addCriterion("maintenance is null");
            return (Criteria) this;
        }

        public Criteria andMaintenanceIsNotNull() {
            addCriterion("maintenance is not null");
            return (Criteria) this;
        }

        public Criteria andMaintenanceEqualTo(String value) {
            addCriterion("maintenance =", value, "maintenance");
            return (Criteria) this;
        }

        public Criteria andMaintenanceNotEqualTo(String value) {
            addCriterion("maintenance <>", value, "maintenance");
            return (Criteria) this;
        }

        public Criteria andMaintenanceGreaterThan(String value) {
            addCriterion("maintenance >", value, "maintenance");
            return (Criteria) this;
        }

        public Criteria andMaintenanceGreaterThanOrEqualTo(String value) {
            addCriterion("maintenance >=", value, "maintenance");
            return (Criteria) this;
        }

        public Criteria andMaintenanceLessThan(String value) {
            addCriterion("maintenance <", value, "maintenance");
            return (Criteria) this;
        }

        public Criteria andMaintenanceLessThanOrEqualTo(String value) {
            addCriterion("maintenance <=", value, "maintenance");
            return (Criteria) this;
        }

        public Criteria andMaintenanceLike(String value) {
            addCriterion("maintenance like", value, "maintenance");
            return (Criteria) this;
        }

        public Criteria andMaintenanceNotLike(String value) {
            addCriterion("maintenance not like", value, "maintenance");
            return (Criteria) this;
        }

        public Criteria andMaintenanceIn(List<String> values) {
            addCriterion("maintenance in", values, "maintenance");
            return (Criteria) this;
        }

        public Criteria andMaintenanceNotIn(List<String> values) {
            addCriterion("maintenance not in", values, "maintenance");
            return (Criteria) this;
        }

        public Criteria andMaintenanceBetween(String value1, String value2) {
            addCriterion("maintenance between", value1, value2, "maintenance");
            return (Criteria) this;
        }

        public Criteria andMaintenanceNotBetween(String value1, String value2) {
            addCriterion("maintenance not between", value1, value2, "maintenance");
            return (Criteria) this;
        }

        public Criteria andCertificationIsNull() {
            addCriterion("certification is null");
            return (Criteria) this;
        }

        public Criteria andCertificationIsNotNull() {
            addCriterion("certification is not null");
            return (Criteria) this;
        }

        public Criteria andCertificationEqualTo(String value) {
            addCriterion("certification =", value, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationNotEqualTo(String value) {
            addCriterion("certification <>", value, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationGreaterThan(String value) {
            addCriterion("certification >", value, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationGreaterThanOrEqualTo(String value) {
            addCriterion("certification >=", value, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationLessThan(String value) {
            addCriterion("certification <", value, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationLessThanOrEqualTo(String value) {
            addCriterion("certification <=", value, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationLike(String value) {
            addCriterion("certification like", value, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationNotLike(String value) {
            addCriterion("certification not like", value, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationIn(List<String> values) {
            addCriterion("certification in", values, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationNotIn(List<String> values) {
            addCriterion("certification not in", values, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationBetween(String value1, String value2) {
            addCriterion("certification between", value1, value2, "certification");
            return (Criteria) this;
        }

        public Criteria andCertificationNotBetween(String value1, String value2) {
            addCriterion("certification not between", value1, value2, "certification");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("created_date is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("created_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("created_date =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("created_date <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("created_date >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("created_date >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("created_date <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("created_date <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("created_date in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("created_date not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("created_date between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("created_date not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedIsNull() {
            addCriterion("last_updated is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedIsNotNull() {
            addCriterion("last_updated is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedEqualTo(Date value) {
            addCriterion("last_updated =", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedNotEqualTo(Date value) {
            addCriterion("last_updated <>", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedGreaterThan(Date value) {
            addCriterion("last_updated >", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("last_updated >=", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedLessThan(Date value) {
            addCriterion("last_updated <", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("last_updated <=", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedIn(List<Date> values) {
            addCriterion("last_updated in", values, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedNotIn(List<Date> values) {
            addCriterion("last_updated not in", values, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedBetween(Date value1, Date value2) {
            addCriterion("last_updated between", value1, value2, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("last_updated not between", value1, value2, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andProductLinkIsNull() {
            addCriterion("product_link is null");
            return (Criteria) this;
        }

        public Criteria andProductLinkIsNotNull() {
            addCriterion("product_link is not null");
            return (Criteria) this;
        }

        public Criteria andProductLinkEqualTo(String value) {
            addCriterion("product_link =", value, "productLink");
            return (Criteria) this;
        }

        public Criteria andProductLinkNotEqualTo(String value) {
            addCriterion("product_link <>", value, "productLink");
            return (Criteria) this;
        }

        public Criteria andProductLinkGreaterThan(String value) {
            addCriterion("product_link >", value, "productLink");
            return (Criteria) this;
        }

        public Criteria andProductLinkGreaterThanOrEqualTo(String value) {
            addCriterion("product_link >=", value, "productLink");
            return (Criteria) this;
        }

        public Criteria andProductLinkLessThan(String value) {
            addCriterion("product_link <", value, "productLink");
            return (Criteria) this;
        }

        public Criteria andProductLinkLessThanOrEqualTo(String value) {
            addCriterion("product_link <=", value, "productLink");
            return (Criteria) this;
        }

        public Criteria andProductLinkLike(String value) {
            addCriterion("product_link like", value, "productLink");
            return (Criteria) this;
        }

        public Criteria andProductLinkNotLike(String value) {
            addCriterion("product_link not like", value, "productLink");
            return (Criteria) this;
        }

        public Criteria andProductLinkIn(List<String> values) {
            addCriterion("product_link in", values, "productLink");
            return (Criteria) this;
        }

        public Criteria andProductLinkNotIn(List<String> values) {
            addCriterion("product_link not in", values, "productLink");
            return (Criteria) this;
        }

        public Criteria andProductLinkBetween(String value1, String value2) {
            addCriterion("product_link between", value1, value2, "productLink");
            return (Criteria) this;
        }

        public Criteria andProductLinkNotBetween(String value1, String value2) {
            addCriterion("product_link not between", value1, value2, "productLink");
            return (Criteria) this;
        }

        public Criteria andOperatingTemperatureIsNull() {
            addCriterion("Operating_temperature is null");
            return (Criteria) this;
        }

        public Criteria andOperatingTemperatureIsNotNull() {
            addCriterion("Operating_temperature is not null");
            return (Criteria) this;
        }

        public Criteria andOperatingTemperatureEqualTo(String value) {
            addCriterion("Operating_temperature =", value, "operatingTemperature");
            return (Criteria) this;
        }

        public Criteria andOperatingTemperatureNotEqualTo(String value) {
            addCriterion("Operating_temperature <>", value, "operatingTemperature");
            return (Criteria) this;
        }

        public Criteria andOperatingTemperatureGreaterThan(String value) {
            addCriterion("Operating_temperature >", value, "operatingTemperature");
            return (Criteria) this;
        }

        public Criteria andOperatingTemperatureGreaterThanOrEqualTo(String value) {
            addCriterion("Operating_temperature >=", value, "operatingTemperature");
            return (Criteria) this;
        }

        public Criteria andOperatingTemperatureLessThan(String value) {
            addCriterion("Operating_temperature <", value, "operatingTemperature");
            return (Criteria) this;
        }

        public Criteria andOperatingTemperatureLessThanOrEqualTo(String value) {
            addCriterion("Operating_temperature <=", value, "operatingTemperature");
            return (Criteria) this;
        }

        public Criteria andOperatingTemperatureLike(String value) {
            addCriterion("Operating_temperature like", value, "operatingTemperature");
            return (Criteria) this;
        }

        public Criteria andOperatingTemperatureNotLike(String value) {
            addCriterion("Operating_temperature not like", value, "operatingTemperature");
            return (Criteria) this;
        }

        public Criteria andOperatingTemperatureIn(List<String> values) {
            addCriterion("Operating_temperature in", values, "operatingTemperature");
            return (Criteria) this;
        }

        public Criteria andOperatingTemperatureNotIn(List<String> values) {
            addCriterion("Operating_temperature not in", values, "operatingTemperature");
            return (Criteria) this;
        }

        public Criteria andOperatingTemperatureBetween(String value1, String value2) {
            addCriterion("Operating_temperature between", value1, value2, "operatingTemperature");
            return (Criteria) this;
        }

        public Criteria andOperatingTemperatureNotBetween(String value1, String value2) {
            addCriterion("Operating_temperature not between", value1, value2, "operatingTemperature");
            return (Criteria) this;
        }

        public Criteria andOperatingRhIsNull() {
            addCriterion("operating_RH is null");
            return (Criteria) this;
        }

        public Criteria andOperatingRhIsNotNull() {
            addCriterion("operating_RH is not null");
            return (Criteria) this;
        }

        public Criteria andOperatingRhEqualTo(String value) {
            addCriterion("operating_RH =", value, "operatingRh");
            return (Criteria) this;
        }

        public Criteria andOperatingRhNotEqualTo(String value) {
            addCriterion("operating_RH <>", value, "operatingRh");
            return (Criteria) this;
        }

        public Criteria andOperatingRhGreaterThan(String value) {
            addCriterion("operating_RH >", value, "operatingRh");
            return (Criteria) this;
        }

        public Criteria andOperatingRhGreaterThanOrEqualTo(String value) {
            addCriterion("operating_RH >=", value, "operatingRh");
            return (Criteria) this;
        }

        public Criteria andOperatingRhLessThan(String value) {
            addCriterion("operating_RH <", value, "operatingRh");
            return (Criteria) this;
        }

        public Criteria andOperatingRhLessThanOrEqualTo(String value) {
            addCriterion("operating_RH <=", value, "operatingRh");
            return (Criteria) this;
        }

        public Criteria andOperatingRhLike(String value) {
            addCriterion("operating_RH like", value, "operatingRh");
            return (Criteria) this;
        }

        public Criteria andOperatingRhNotLike(String value) {
            addCriterion("operating_RH not like", value, "operatingRh");
            return (Criteria) this;
        }

        public Criteria andOperatingRhIn(List<String> values) {
            addCriterion("operating_RH in", values, "operatingRh");
            return (Criteria) this;
        }

        public Criteria andOperatingRhNotIn(List<String> values) {
            addCriterion("operating_RH not in", values, "operatingRh");
            return (Criteria) this;
        }

        public Criteria andOperatingRhBetween(String value1, String value2) {
            addCriterion("operating_RH between", value1, value2, "operatingRh");
            return (Criteria) this;
        }

        public Criteria andOperatingRhNotBetween(String value1, String value2) {
            addCriterion("operating_RH not between", value1, value2, "operatingRh");
            return (Criteria) this;
        }

        public Criteria andOthersIsNull() {
            addCriterion("others is null");
            return (Criteria) this;
        }

        public Criteria andOthersIsNotNull() {
            addCriterion("others is not null");
            return (Criteria) this;
        }

        public Criteria andOthersEqualTo(String value) {
            addCriterion("others =", value, "others");
            return (Criteria) this;
        }

        public Criteria andOthersNotEqualTo(String value) {
            addCriterion("others <>", value, "others");
            return (Criteria) this;
        }

        public Criteria andOthersGreaterThan(String value) {
            addCriterion("others >", value, "others");
            return (Criteria) this;
        }

        public Criteria andOthersGreaterThanOrEqualTo(String value) {
            addCriterion("others >=", value, "others");
            return (Criteria) this;
        }

        public Criteria andOthersLessThan(String value) {
            addCriterion("others <", value, "others");
            return (Criteria) this;
        }

        public Criteria andOthersLessThanOrEqualTo(String value) {
            addCriterion("others <=", value, "others");
            return (Criteria) this;
        }

        public Criteria andOthersLike(String value) {
            addCriterion("others like", value, "others");
            return (Criteria) this;
        }

        public Criteria andOthersNotLike(String value) {
            addCriterion("others not like", value, "others");
            return (Criteria) this;
        }

        public Criteria andOthersIn(List<String> values) {
            addCriterion("others in", values, "others");
            return (Criteria) this;
        }

        public Criteria andOthersNotIn(List<String> values) {
            addCriterion("others not in", values, "others");
            return (Criteria) this;
        }

        public Criteria andOthersBetween(String value1, String value2) {
            addCriterion("others between", value1, value2, "others");
            return (Criteria) this;
        }

        public Criteria andOthersNotBetween(String value1, String value2) {
            addCriterion("others not between", value1, value2, "others");
            return (Criteria) this;
        }

        public Criteria andPictureIsNull() {
            addCriterion("picture is null");
            return (Criteria) this;
        }

        public Criteria andPictureIsNotNull() {
            addCriterion("picture is not null");
            return (Criteria) this;
        }

        public Criteria andPictureEqualTo(String value) {
            addCriterion("picture =", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotEqualTo(String value) {
            addCriterion("picture <>", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThan(String value) {
            addCriterion("picture >", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThanOrEqualTo(String value) {
            addCriterion("picture >=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThan(String value) {
            addCriterion("picture <", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThanOrEqualTo(String value) {
            addCriterion("picture <=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLike(String value) {
            addCriterion("picture like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotLike(String value) {
            addCriterion("picture not like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureIn(List<String> values) {
            addCriterion("picture in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotIn(List<String> values) {
            addCriterion("picture not in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureBetween(String value1, String value2) {
            addCriterion("picture between", value1, value2, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotBetween(String value1, String value2) {
            addCriterion("picture not between", value1, value2, "picture");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ledpanel
     *
     * @mbg.generated do_not_delete_during_merge Fri Jan 18 20:04:23 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ledpanel
     *
     * @mbg.generated Fri Jan 18 20:04:23 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}